export const healthcareSkillSuggestions = [
  "Phlebotomy",
  "Electrocardiography (EKG/ECG)",
  "Medical Coding (ICD-10/CPT)",
  "Electronic Health Records (EHR) Management",
  "HIPAA Compliance",
  "Vital Signs Monitoring",
  "CPR Certification",
  "Advanced Cardiac Life Support (ACLS)",
  "Patient Triage",
  "Wound Care Management",
  "Medication Administration",
  "Intravenous (IV) Therapy",
  "Surgical Instrument Sterilization",
  "Medical Billing",
  "Health Informatics",
  "Clinical Documentation",
  "Patient Scheduling",
  "Radiology Imaging (X-ray, MRI, CT)",
  "Ultrasound Technology",
  "Respiratory Therapy",
  "Physical Therapy Techniques",
  "Occupational Therapy Interventions",
  "Speech-Language Pathology",
  "Medical Transcription",
  "Healthcare Data Analytics",
  "Telehealth Coordination",
  "Infection Control Procedures",
  "Central Line Care",
  "Catheterization",
  "Dialysis Technology",
  "Chemotherapy Administration",
  "Pain Management Techniques",
  "Diabetes Education",
  "Nutritional Counseling",
  "Behavioral Health Assessment",
  "Mental Health First Aid",
  "Substance Abuse Counseling",
  "Case Management",
  "Care Plan Development",
  "Patient Advocacy",
  "Teaching",
  "Medical Equipment Calibration",
  "Laboratory Sample Analysis",
  "Microbiology Testing",
  "Hematology Analysis",
  "Pathology Assistance",
  "Pharmacology Knowledge",
  "Prescription Verification",
  "Compounding Medications",
  "Anesthesia Monitoring",
  "Surgical First Assisting",
  "Endoscopy Assistance",
  "Cardiac Catheterization",
  "EHR Software (Epic, Cerner)",
  "Medical Scribe",
  "Healthcare Quality Improvement",
  "Risk Management in Healthcare",
  "Patient Safety Protocols",
  "Regulatory Compliance (OSHA, CMS)",
  "Medical Device Sales",
  "Healthcare Marketing",
  "Patient Experience Management",
  "Revenue Cycle Management",
  "Healthcare Policy Analysis",
  "Clinical Trial Coordination",
  "IRB Submission Processes",
  "Good Clinical Practice (GCP)",
  "Biomedical Equipment Maintenance",
  "Health Information Exchange (HIE)",
  "Interoperability Standards (HL7, FHIR)",
  "Medical Imaging Software",
  "PACS Administration",
  "Echocardiography",
  "Neonatal Resuscitation",
  "Pediatric Advanced Life Support (PALS)",
  "Geriatric Care Management",
  "Palliative Care Techniques",
  "Hospice Care Coordination",
  "Orthopedic Casting",
  "Prosthetics Fitting",
  "Rehabilitation Therapy Planning",
  "Cardiopulmonary Rehabilitation",
  "Stroke Recovery Support",
  "Trauma Care",
  "Burn Care Management",
  "Sepsis Management",
  "Ventilator Management",
  "Telemetry Monitoring",
  "Wound Vac Application",
  "Ostomy Care",
  "Enteral Feeding",
  "Parenteral Nutrition Management",
  "Blood Transfusion Administration",
  "Oncology Nursing",
  "Radiotherapy Assistance",
  "Genetic Counseling",
  "Healthcare IT Support",
  "Cybersecurity in Healthcare",
  "Medical Supply Chain Management",
  "Healthcare Facility Management",
  "Patient Flow Optimization",
  "Lean Six Sigma in Healthcare",
];
