import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { Toaster } from "sonner";
import ReduxProvider from "@/redux/Provider";
import Loading from "@/components/Others/Loading";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}  className={rubik.className}>
        <ReduxProvider>
          <Toaster position="top-center" expand={true} richColors />
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </ReduxProvider>
      </body>
    </html>
  );
}
