

import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { Toaster } from "sonner";
import ReduxProvider from "@/redux/Provider";
import Loading from "@/components/Others/Loading";
import { GoogleOAuthProvider } from "@react-oauth/google";
import GoogleTranslateProvider from "@/components/shared/googleTranslation/GoogleLang";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Julientmts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={rubik.variable}>
        {/* <body
        suppressHydrationWarning={true}
        className={`${rubik.variable} antialiased relative! z-20 top-0!`}
        style={{ position: "static", top: "0" }}
      > */}
        <div suppressHydrationWarning className="bg-[#FFFFFF]">
          <GoogleTranslateProvider>
            <ReduxProvider>
              <Toaster position="top-center" expand={true} richColors />
              <GoogleOAuthProvider
                clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}
              >
                <Suspense fallback={<Loading />}>{children}</Suspense>
              </GoogleOAuthProvider>
            </ReduxProvider>
          </GoogleTranslateProvider>
        </div>
      </body>
    </html>
  );
}

